# Generated by Django 2.2.13 on 2021-01-23 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20200913_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friend',
            field=models.ManyToManyField(blank=True, null=True, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Друг'),
        ),
    ]
